# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import enviro.models
import enviro.validators


class Migration(migrations.Migration):

    dependencies = [
        ('enviro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurefilemodel',
            name='measure_file',
            field=models.FileField(upload_to=enviro.models.measurement_directory_path, validators=[enviro.validators.validate_file_extension]),
        ),
    ]
