# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enviro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalContourOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContourPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EEDCScalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalContour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitting_method', models.CharField(max_length=240)),
                ('contour_method', models.CharField(max_length=240)),
                ('return_period', models.CharField(max_length=240)),
                ('state_duration', models.CharField(max_length=240)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enviro.ProbabilisticModel')),
            ],
        ),
        migrations.CreateModel(
            name='ExtremeEnvDesignCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contour_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enviro.ContourPath')),
            ],
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='function',
            field=models.CharField(choices=[(None, 'None'), ('f1', 'power function'), ('f2', 'exponential')], max_length=6),
        ),
        migrations.AddField(
            model_name='eedcscalar',
            name='contour_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enviro.ExtremeEnvDesignCondition'),
        ),
        migrations.AddField(
            model_name='contourpath',
            name='environmental_contour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enviro.EnvironmentalContour'),
        ),
        migrations.AddField(
            model_name='additionalcontouroption',
            name='environmental_contour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enviro.EnvironmentalContour'),
        ),
    ]
