# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionmodel',
            name='symbol',
            field=models.CharField(default='[p]', max_length=5),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='x0',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='x1',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='x2',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
    ]
