# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enviro.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enviro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='MeasureFile', max_length=50)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('measure_file', models.FileField(upload_to='', validators=[enviro.validators.validate_file_extension])),
                ('primary_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary', to=settings.AUTH_USER_MODEL)),
                ('secondary_user', models.ManyToManyField(max_length=50, related_name='secondary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='measurefilemanager',
            name='primary_user',
        ),
        migrations.RemoveField(
            model_name='measurefilemanager',
            name='secondary_user',
        ),
        migrations.AddField(
            model_name='distributionmodel',
            name='symbol',
            field=models.CharField(default='Tp', max_length=5),
        ),
        migrations.AlterField(
            model_name='distributionmodel',
            name='distribution',
            field=models.CharField(choices=[('Normal', 'Normal Distribution'), ('Weibull', 'Weibull'), ('Lognormal_2', 'Log-Normal'), ('KernelDensity', 'Kernel Density')], max_length=15),
        ),
        migrations.AlterField(
            model_name='distributionmodel',
            name='name',
            field=models.CharField(default='peak period', max_length=50),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='x0',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='x1',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='x2',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='MeasureFileManager',
        ),
        migrations.AddField(
            model_name='probabilisticmodel',
            name='measure_file_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enviro.MeasureFileModel'),
        ),
    ]
