# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviro', '0002_auto_20170922_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionmodel',
            name='distribution',
            field=models.CharField(choices=[('Normal', 'Normal Distribution'), ('Weibull', 'Weibull'), ('Lognormal_1', 'Log-Normal'), ('KernelDensity', 'Kernel Density')], max_length=15),
        ),
        migrations.AlterField(
            model_name='distributionmodel',
            name='symbol',
            field=models.CharField(default='p', max_length=5),
        ),
    ]
