# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviro', '0002_auto_20180222_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentalcontour',
            old_name='distribution',
            new_name='probabilistic_model',
        ),
        migrations.AlterField(
            model_name='environmentalcontour',
            name='return_period',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='environmentalcontour',
            name='state_duration',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
