# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enviro', '0003_auto_20180226_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalcontouroption',
            old_name='environmental_contour',
            new_name='environmental_contour_pk',
        ),
        migrations.RenameField(
            model_name='contourpath',
            old_name='environmental_contour',
            new_name='environmental_contour_pk',
        ),
        migrations.RenameField(
            model_name='eedcscalar',
            old_name='contour_path',
            new_name='EEDC_pk',
        ),
        migrations.RenameField(
            model_name='environmentalcontour',
            old_name='probabilistic_model',
            new_name='probabilistic_model_pk',
        ),
        migrations.RenameField(
            model_name='extremeenvdesigncondition',
            old_name='contour_path',
            new_name='contour_path_pk',
        ),
    ]
