# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviro', '0004_auto_20180226_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcontouroption',
            name='option_key',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='additionalcontouroption',
            name='option_value',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
