# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviro', '0004_auto_20170925_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionmodel',
            name='name',
            field=models.CharField(default='peak period', max_length=50),
        ),
        migrations.AlterField(
            model_name='measurefilemanager',
            name='secondary_user',
            field=models.ManyToManyField(max_length=50, related_name='secondary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='measurefilemanager',
            name='title',
            field=models.CharField(default='MeasureFile', max_length=50),
        ),
    ]
