# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enviro', '0005_auto_20171027_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeasureFileManager',
            new_name='MeasureFileModel',
        ),
        migrations.AddField(
            model_name='probabilisticmodel',
            name='measure_file_model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enviro.MeasureFileModel'),
            preserve_default=False,
        ),
    ]
