# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enviro', '0006_auto_20171107_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probabilisticmodel',
            name='measure_file_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enviro.MeasureFileModel'),
        ),
    ]
