# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import contour.models
import contour.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurefilemodel',
            name='measure_file',
            field=models.FileField(upload_to=contour.models.image_directory_path, validators=[contour.validators.validate_file_extension]),
        ),
    ]
