# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contour', '0002_auto_20180307_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalcontour',
            name='primary_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contours_primary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='environmentalcontour',
            name='secondary_user',
            field=models.ManyToManyField(related_name='contours_secondary', to=settings.AUTH_USER_MODEL),
        ),
    ]
