# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 13:45
from __future__ import unicode_literals

from django.db import migrations
from user.models import User


def load_data(apps, schema_editor):
    """
    Seed the data base using data migration, see
    https://docs.djangoproject.com/en/2.0/topics/migrations/#data-migrations

    Parameters
    ----------
    apps : django.apps,
        Design pattern from https://docs.djangoproject.com/en/2.0/howto/
        writing-migrations/
    schema_editor : SchemaEditor,
        Design pattern from https://docs.djangoproject.com/en/2.0/howto/
        writing-migrations/
        Also see: https://docs.djangoproject.com/en/2.0/ref/schema-editor
    """
    # Do not use the historic version of User since it cannot not use the
    # set_password method in that case
    #User = apps.get_model('user', 'User')
    user = User(
        username='max_mustermann',
        email='max.mustermann@gmail.com',
        first_name='Max',
        last_name='Mustermann',
        organisation='Musterfirma',
        type_of_use='commercial'
    )
    user.save()
    user.set_password('Musterpasswort2018')
    user.save()
    user = User(
        username='sabine_mustermann',
        email='sabine.mustermann@gmail.com',
        first_name='Sabine',
        last_name='Mustermann',
        organisation='Musterfirma',
        type_of_use='academic',
        password='Musterpasswort2018',
    )
    user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('contour', '0003_auto_20180307_1652'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
