# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contour', '0004_auto_20180402_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurefilemodel',
            name='scatter_plot',
            field=models.ImageField(default=None, null=True, upload_to='<function measurement_directory_path at 0x102b77488>_scatter_plot'),
        ),
    ]
