# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contour', '0004_auto_20180409_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionmodel',
            name='distribution',
            field=models.CharField(choices=[('Normal', 'Normal Distribution'), ('Weibull', 'Weibull'), ('Lognormal_2', 'Log-Normal'), ('KernelDensity', 'Kernel Density')], max_length=15),
        ),
    ]
