# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 15:10
from __future__ import unicode_literals

import contour.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contour', '0005_measurefilemodel_scatter_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurefilemodel',
            name='scatter_plot',
            field=models.ImageField(default=None, null=True, upload_to=contour.models.image_directory_path),
        ),
    ]
