# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contour', '0007_plottedfigure'),
    ]

    operations = [
        migrations.AddField(
            model_name='plottedfigure',
            name='environmental_contour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contour.EnvironmentalContour'),
        ),
        migrations.AlterField(
            model_name='plottedfigure',
            name='probabilistic_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contour.ProbabilisticModel'),
        ),
    ]
