# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 15:07
from __future__ import unicode_literals

import contour.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contour', '0008_auto_20180413_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalcontour',
            name='latex_report',
            field=models.FileField(default=None, null=True, upload_to=contour.models.media_directory_path),
        ),
    ]
