# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 08:46
from __future__ import unicode_literals

import contour.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contour', '0009_environmentalcontour_latex_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalcontour',
            name='design_conditions_csv',
            field=models.FileField(default=None, null=True, upload_to=contour.models.media_directory_path),
        ),
    ]
