# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contour', '0011_plottedfigure_distribution_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='plottedfigure',
            name='parameter_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contour.ParameterModel'),
        ),
    ]
