# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 12:23
from __future__ import unicode_literals

import contour.models
import contour.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contour', '0012_plottedfigure_parameter_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurefilemodel',
            name='measure_file',
            field=models.FileField(max_length=120, upload_to=contour.models.media_directory_path, validators=[contour.validators.validate_csv_upload]),
        ),
    ]
