# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171218_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_of_use',
            field=models.CharField(choices=[('academic', 'academic'), ('commercial', 'commercial')], max_length=11),
        ),
    ]
